logging:
  level:
    io.netty.resolver.dns.DnsServerAddressStreamProviders: OFF
    root: OFF
spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat.options.model: gpt-4o-mini
    session:
      repository.jdbc.initialize-schema: always
  application:
    name: coding-agent
  main:
    banner-mode: off
    web-application-type: none
